Practice5_WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Practice5_Model.Models;
using System.Diagnostics;

namespace Practice5_WebApp.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Practice5_WebApp/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Mvc;
using Practice5_DataAccess.Data;
using Practice5_Model.Models;

namespace Practice5_WebApp.Controllers
{
	public class InventoryController : Controller
	{
		private readonly ApplicationDbContext _db;

		public InventoryController(ApplicationDbContext db)
		{

			_db = db;
		}
		public IActionResult Index()
		{
			List<Inventory> objList = _db.Inventories.ToList();

			return View(objList);
		}

		public IActionResult Upsert(int? id)
		{
			Inventory obj = new Inventory();
			if (id == null || id == 0)
			{
				//Create
				return View(obj);
			}
			//Edit
			obj = _db.Inventories.First(p => p.Inventory_Id == id);
			if (obj == null)
			{
				return NotFound();
			}
			return View(obj);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(Inventory obj)
		{
			if (obj.Inventory_Id == 0)
			{
				//Create
				_db.Inventories.Add(obj);
			}
			else
			{
				//Update
				_db.Inventories.Update(obj);
			}
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult Delete(int id)
		{
			Inventory obj = new Inventory();
			//Edit
			obj = _db.Inventories.First(p => p.Inventory_Id == id);
			if (obj == null)
			{
				return NotFound();
			}

			_db.Inventories.Remove(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Practice5_WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Practice5_DataAccess.Data;
using Practice5_Model.Models;

namespace Practice5_WebApp.Controllers
{
	public class ProductController : Controller
	{

		private readonly ApplicationDbContext _db;

		public ProductController(ApplicationDbContext db)
		{

			_db = db;
		}
		public IActionResult Index()
		{
			List<Product> objList = _db.Products.ToList();

			return View(objList);
		}

		public IActionResult Upsert(int? id)
		{
			Product obj = new Product();
			if (id == null || id == 0)
			{
				//Create
				return View(obj);
			}
			//Edit
			obj = _db.Products.First(p => p.Product_Id == id);
			if (obj == null)
			{
				return NotFound();
			}
			return View(obj);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Upsert(Product obj)
		{
			if (obj.Product_Id == 0)
			{
				//Create
				await _db.Products.AddAsync(obj);
			}
			else
			{
				//Update
				_db.Products.Update(obj);
			}
			_db.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		public IActionResult Delete(int id)
		{
			Product obj = new Product();
			//Edit
			obj = _db.Products.First(p => p.Product_Id == id);
			if (obj == null)
			{
				return NotFound();
			}

			_db.Products.Remove(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Practice5_WebApp/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Practice5_DataAccess.Data;
using Practice5_Model.Models;

namespace Practice5_WebApp.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PurchaseController(ApplicationDbContext db)
        {

            _db = db;
        }
        public IActionResult Index()
        {
            List<Purchase> objList = _db.Purchases.ToList();

            return View(objList);
        }

        public IActionResult Upsert(int? id)
        {
            Purchase obj = new Purchase();
            if (id == null || id == 0)
            {
                //Create
                return View(obj);
            }
            //Edit
            obj = _db.Purchases.First(p => p.Purchase_Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Purchase obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Product_Id == 0)
                {
                    //Create
                    _db.Purchases.Add(obj);
                }
                else
                {
                    //Update
                    _db.Purchases.Update(obj);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int id)
        {
            Purchase obj = new Purchase();
            //Edit
            obj = _db.Purchases.First(p => p.Product_Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Purchases.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Practice5_WebApp/Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using Practice5_DataAccess.Data;
using Practice5_Model.Models;

namespace Practice5_WebApp.Controllers
{
	public class SaleController : Controller
	{

		private readonly ApplicationDbContext _db;

		public SaleController(ApplicationDbContext db)
		{

			_db = db;
		}

		public IActionResult SaleIndex()
		{
			List<Sale> objList = _db.Sales.ToList();

			return View(objList);
		}
		public IActionResult Upsert(int? id)
		{
			Sale obj = new Sale();
			if (id == null || id == 0)
			{
				//Create
				return View(obj);
			}
			//Edit
			obj = _db.Sales.First(p => p.Sale_Id == id);
			if (obj == null)
			{
				return NotFound();
			}
			return View(obj);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(Sale obj)
		{
			if (obj.Sale_Id == 0)
			{
				//Create
				_db.Sales.Add(obj);
			}
			else
			{
				//Update
				_db.Sales.Update(obj);
			}
			_db.SaveChanges();
			return RedirectToAction("SaleIndex");
		}

		public IActionResult Delete(int id)
		{
			Sale obj = new Sale();
			//Edit
			obj = _db.Sales.First(p => p.Sale_Id == id);
			if (obj == null)
			{
				return NotFound();
			}

			_db.Sales.Remove(obj);
			_db.SaveChanges();
			return RedirectToAction("SaleIndex");
		}
	}
}

Practice5_WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Practice5_WebApp/Views/Inventory/Index.cshtml
@model IEnumerable<Practice5_Model.Models.Inventory>

<br />
<br />
<div class="border p-4 bg-white">
	<div class="row">
		<div class="col-9">
			<h2 class="text-info"> Inventory List</h2>
		</div>

		<div class="col-3 text-right">
			<a asp-action="Upsert" class="btn btn-info form-control"> Create New </a>
		</div>
	</div>
	</div>
	<br />
	<div>
	@if (Model.Count() > 0)
	{
										<table class="table table-striped border">
											<tr class="table-secondary">
												<th>
													Product
												</th>
													<th>
													   Stock
													</th>
												<th></th>
											</tr>
			@foreach (var item in Model)
			{
																			<tr>
																				<td>
						@item.Product_Id
																				</td>
																						 <td>
						@item.Stock
																						</td>
																				<td>
																					<a class="btn btn-primary text-white" asp-action="Upsert" asp-route-Id="@item.Inventory_Id">
																					   Edit
																					</a>

																					<a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@item.Inventory_Id">
																						Delete
																					</a>
																				</td>
																			</tr>
			}
										</table>
	}
	else
	{
										<p>No Product exists...</p>
	}
	</div>
</div>

Practice5_WebApp/Views/Inventory/Upsert.cshtml
@model Practice5_Model.Models.Inventory

@{
	var title = "Create Inventory";
}

<form method="post">
	<div class="row p-3 border">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<input type="hidden" asp-for="Inventory_Id" />
		@if (Model.Inventory_Id != 0)
		{
			title = "Edit Inventory";
		}
		<div class="col-12 border-bottom">
			<h2 class="text-primary">@title</h2>
		</div>
		<div class="col-8 pt-4">
			<div class="form-group row py-2">
				<div class="col-4">
					<label asp-for="Product_Id"></label>
				</div>
				<div class="col-8">
					<input asp-for="Product_Id" class="form-control" />
					<span asp-validation-for="Product_Id" class="text-danger"></span>
				</div>
				<div class="col-4">
					<label asp-for="Stock"></label>
				</div>
				<div class="col-8">
					<input asp-for="Stock" class="form-control" />
					<span asp-validation-for="Stock" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-4 offset-4">
					@if (Model.Inventory_Id != 0)
					{
									<button type="submit" class="btn btn-primary form-control">Update</button>
					}
					else
					{
									<button type="submit" class="btn btn-primary form-control">Create</button>
					}
				</div>
				<div class="col-4">
					<a asp-action="Index" class="btn btn-success form-control">Back to List</a>
				</div>
			</div>
		</div>
	</div>
</form>

@section Scripts {
				<partial name="_ValidationScriptsPartial" />
}

Practice5_WebApp/Views/Product/Index.cshtml
@model IEnumerable<Practice5_Model.Models.Product>

<br />
<br />
<div class="border p-4 bg-white">
	<div class="row">
		<div class="col-9">
			<h2 class="text-info"> Product List</h2>
		</div>

		<div class="col-3 text-right">
			<a asp-action="Upsert" class="btn btn-info form-control"> Create New </a>
		</div>
	</div>
	</div>
	<br />
	<div>
	@if (Model.Count() > 0)
	{
								<table class="table table-striped border">
									<tr class="table-secondary">
											<th>
												Product Id
											</th>
										<th>
											Product Name
										</th>
											<th>
											   Description
											</th>
												<th>
												Price
											</th>
												<th>
												QuantityInStock
											</th>
										<th></th>
									</tr>
			@foreach (var item in Model)
			{
															<tr>
																		<td>
						@item.Product_Id
																		</td>
																<td>
						@item.ProductName
																</td>
																		 <td>
						@item.Description
																		</td>
																				 <td>
						@item.Price
																		</td>
																				 <td>
						@item.QuantityInStock
																		</td>
																<td>
																	<a class="btn btn-primary text-white" asp-action="Upsert" asp-route-Id="@item.Product_Id">
																	   Edit
																	</a>

																	<a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@item.Product_Id">
																		Delete
																	</a>
																</td>
															</tr>
			}
								</table>
	}
	else
	{
								<p>No Product exists...</p>
	}
	</div>
</div>

Practice5_WebApp/Views/Product/Upsert.cshtml
@model Practice5_Model.Models.Product

@{
    var title = "Create Product";
}

<form method="post">
    @Html.AntiForgeryToken()
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Product_Id" />
        @if (Model.Product_Id != 0)
        {
            title = "Edit Product";
        }
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="ProductName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ProductName" class="form-control" />
                    <span asp-validation-for="ProductName" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="Description"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="QuantityInStock"></label>
                </div>
                <div class="col-8">
                    <input asp-for="QuantityInStock" class="form-control" />
                    <span asp-validation-for="QuantityInStock" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4 offset-4">
                    @if (Model.Product_Id != 0)
                    {
                            <button type="submit" class="btn btn-primary form-control">Update</button>
                    }
                    else
                    {
                            <button type="submit" class="btn btn-primary form-control">Create</button>
                    }
                </div>
                <div class="col-4">
                    <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
        <partial name="_ValidationScriptsPartial" />
}

Practice5_WebApp/Views/Purchase/Index.cshtml
@model IEnumerable<Practice5_Model.Models.Purchase>

<br />
<br />
<div class="border p-4 bg-white">
	<div class="row">
		<div class="col-9">
			<h2 class="text-info"> Purchase List</h2>
		</div>

		<div class="col-3 text-right">
			<a asp-action="Upsert" class="btn btn-info form-control"> Create New </a>
		</div>
	</div>
	</div>
	<br />
	<div>
	@if (Model.Count() > 0)
	{
														<table class="table table-striped border">
															<tr class="table-secondary">
																<th>
																	Purchase Quantity
																</th>
																	<th>
																	   Purchase Date
																	</th>
																		<th>
																		Purchase Price
																	</th>
																		<th>
																		Total Cost
																	</th>
																	<th>
																		Product Id
																	</th>
															</tr>
			@foreach (var item in Model)
			{
																											<tr>
																												<td>
						@item.QuantityPurchased
																												</td>
																														 <td>
						@item.PurchaseDate
																														</td>
																																 <td>
						@item.PurchasePrice
																														</td>
																																 <td>
						@item.TotalCost
																														</td>
																																	 <td>
						@item.Product_Id
																																</td>
																												<td>
																													<a class="btn btn-primary text-white" asp-action="Upsert" asp-route-Id="@item.Purchase_Id">
																													   Edit
																													</a>

																													<a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@item.Purchase_Id">
																														Delete
																													</a>
																												</td>
																											</tr>
			}
														</table>
	}
	else
	{
														<p>No Sales exists...</p>
	}
	</div>
</div>

Practice5_WebApp/Views/Purchase/Upsert.cshtml
@model Practice5_Model.Models.Purchase

@{
    var title = "Create Purchase";
}

<form method="post">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Purchase_Id" />
        @if (Model.Purchase_Id != 0)
        {
            title = "Edit Purchase";
        }
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="QuantityPurchased"></label>
                </div>
                <div class="col-8">
                    <input asp-for="QuantityPurchased" class="form-control" />
                    <span asp-validation-for="QuantityPurchased" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="PurchasePrice"></label>
                </div>
                <div class="col-8">
                    <input asp-for="PurchasePrice" class="form-control" />
                    <span asp-validation-for="PurchasePrice" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="PurchaseDate"></label>
                </div>
                <div class="col-8">
                    <input asp-for="PurchaseDate" class="form-control" />
                    <span asp-validation-for="PurchaseDate" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="TotalCost"></label>
                </div>
                <div class="col-8">
                    <input asp-for="TotalCost" class="form-control" />
                    <span asp-validation-for="TotalCost" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="Product_Id"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Product_Id" class="form-control" />
                    <span asp-validation-for="Product_Id" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4 offset-4">
                    @if (Model.Purchase_Id != 0)
                    {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                    }
                    else
                    {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                    }
                </div>
                <div class="col-4">
                    <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
                <partial name="_ValidationScriptsPartial" />
}

Practice5_WebApp/Views/Sale/SaleIndex.cshtml
@model IEnumerable<Practice5_Model.Models.Sale>

<br />
<br />
<div class="border p-4 bg-white">
	<div class="row">
		<div class="col-9">
			<h2 class="text-info"> Sale List</h2>
		</div>

		<div class="col-3 text-right">
			<a asp-action="Upsert" class="btn btn-info form-control"> Create New </a>
		</div>
	</div>
	</div>
	<br />
	<div>
	@if (Model.Count() > 0)
	{
										<table class="table table-striped border">
											<tr class="table-secondary">
												<th>
													Sale Quantity
												</th>
													<th>
													   Sale Date
													</th>
														<th>
														Sale Price
													</th>
														<th>
														Total Amount
													</th>
												<th>Customer Name</th>
													<th>Product Id</th>
											</tr>
			@foreach (var item in Model)
			{
																			<tr>
																				<td>
						@item.QuantitySold
																				</td>
																						 <td>
						@item.SaleDate
																						</td>
																								 <td>
						@item.SalePrice
																								</td>
																								 <td>
						@item.TotalAmount
																						</td>
																								 <td>
						@item.CustomerName
																						</td>
																									 <td>
						@item.Product_Id
																								</td>
																				<td>
																					<a class="btn btn-primary text-white" asp-action="Upsert" asp-route-Id="@item.Sale_Id">
																					   Edit
																					</a>

																					<a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@item.Sale_Id">
																						Delete
																					</a>
																				</td>
																			</tr>
			}
										</table>
	}
	else
	{
										<p>No Sales exists...</p>
	}
	</div>
</div>

Practice5_WebApp/Views/Sale/Upsert.cshtml
@model Practice5_Model.Models.Sale

@{
    var title = "Create Sale";
}

<form method="post">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Sale_Id" />
        @if (Model.Sale_Id != 0)
        {
            title = "Edit Sale";
        }
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="QuantitySold"></label>
                </div>
                <div class="col-8">
                    <input asp-for="QuantitySold" class="form-control" />
                    <span asp-validation-for="QuantitySold" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="SaleDate"></label>
                </div>
                <div class="col-8">
                    <input asp-for="SaleDate" class="form-control" />
                    <span asp-validation-for="SaleDate" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="SalePrice"></label>
                </div>
                <div class="col-8">
                    <input asp-for="SalePrice" class="form-control" />
                    <span asp-validation-for="SalePrice" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="TotalAmount"></label>
                </div>
                <div class="col-8">
                    <input asp-for="TotalAmount" class="form-control" />
                    <span asp-validation-for="TotalAmount" class="text-danger"></span>
                </div>
                <div class="col-4">
                    <label asp-for="CustomerName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                 <div class="col-4">
                    <label asp-for="Product_Id"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Product_Id" class="form-control" />
                    <span asp-validation-for="Product_Id" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4 offset-4">
                    @if (Model.Sale_Id != 0)
                    {
                                <button type="submit" class="btn btn-primary form-control">Update</button>
                    }
                    else
                    {
                                <button type="submit" class="btn btn-primary form-control">Create</button>
                    }
                </div>
                <div class="col-4">
                    <a asp-action="SaleIndex" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
            <partial name="_ValidationScriptsPartial" />
}

Practice5_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practice5_WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practice5_WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practice5_WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="SaleIndex">Sales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="Index">Purchases</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">Inventory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Practice5_WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>